project_id = "xcauajpfrmalzhhiodcb"

[functions.detect-pet-breed]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.analyze-training-submission]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-demo-users]
verify_jwt = false

[functions.smart-discovery]
verify_jwt = false
