create table if not exists public.product_variations (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.scraped_products(id) on delete cascade,
  variation_name text not null,
  variation_value text,
  variation_price numeric(10,2),
  variation_sku text,
  variation_stock_status public.stock_status default 'unknown',
  created_at timestamptz default now()
);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid references public.scraped_products(id) on delete cascade,
  image_url text not null,
  alt_text text,
  is_main boolean default false,
  display_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.scraping_jobs (
  id uuid primary key default gen_random_uuid(),
  base_url text not null,
  status text default 'pending',
  total_pages integer default 0,
  scraped_pages integer default 0,
  total_products integer default 0,
  scraped_products integer default 0,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_product_variations_product on public.product_variations(product_id);
create index if not exists idx_product_images_product on public.product_images(product_id);
create index if not exists idx_scraping_jobs_status on public.scraping_jobs(status);

insert into public.business_profiles (
  id,
  business_name,
  business_type,
  description,
  email,
  website,
  city,
  is_verified,
  is_featured
) values (
  'cf941cc4-e1d1-4d7c-8122-a5df81a1e53c',
  'MIPO Shop',
  'shop',
  'Default MIPO shop business profile for product catalog management.',
  'shop@mipo.pet',
  'https://mipo.pet',
  'Israel',
  true,
  true
) on conflict (id) do update set
  business_name = excluded.business_name,
  description = excluded.description,
  email = excluded.email,
  website = excluded.website,
  updated_at = now();

with seed_products (
  sku,
  name,
  description,
  price,
  original_price,
  sale_price,
  image_url,
  category,
  pet_type,
  is_featured,
  flavors,
  brand,
  weight_unit,
  price_per_weight,
  ingredients,
  benefits,
  product_attributes,
  life_stage,
  dog_size,
  special_diet,
  breed_tags,
  medical_tags,
  safety_score,
  kcal_per_kg
) as (
  values
    (
      'MIPO-DOG-FOOD-001',
      'MIPO Daily Chicken לכלבים',
      'מזון יבש מאוזן לכלבים בוגרים עם עוף, אורז וסיבים לעיכול יומיומי.',
      219.90::numeric,
      249.90::numeric,
      199.90::numeric,
      'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=900&auto=format&fit=crop',
      'מזון',
      'dog'::public.pet_type,
      true,
      array['עוף', 'אורז']::text[],
      'MIPO',
      '12 ק״ג',
      16.66::numeric,
      'עוף מיובש, אורז, שיבולת שועל, שמן סלמון, ויטמינים ומינרלים',
      '["תמיכה בעיכול", "פרווה מבריקה", "אנרגיה יומיומית"]'::jsonb,
      '{"protein": "26%", "fat": "14%"}'::jsonb,
      'adult',
      'medium',
      array[]::text[],
      array['לברדור', 'גולדן רטריבר', 'כלב מעורב']::text[],
      array['עיכול']::text[],
      92::numeric,
      3650::numeric
    ),
    (
      'MIPO-CAT-FOOD-001',
      'MIPO Salmon Indoor לחתולים',
      'מזון יבש לחתולי בית עם סלמון, טאורין ותמיכה בכדורי שיער.',
      149.90::numeric,
      169.90::numeric,
      139.90::numeric,
      'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=900&auto=format&fit=crop',
      'מזון',
      'cat'::public.pet_type,
      true,
      array['סלמון']::text[],
      'MIPO',
      '3 ק״ג',
      46.63::numeric,
      'סלמון, אורז, אפונה, טאורין, שמן דגים, סיבים טבעיים',
      '["תמיכה בלב", "הפחתת כדורי שיער", "מתאים לבית"]'::jsonb,
      '{"protein": "32%", "fat": "15%"}'::jsonb,
      'adult',
      null,
      array[]::text[],
      array['חתול בית', 'פרסי', 'סיאמי']::text[],
      array['עור', 'לב']::text[],
      90::numeric,
      3900::numeric
    ),
    (
      'MIPO-DOG-TREATS-001',
      'חטיפי אילוף עוף רכים',
      'חטיפים קטנים ורכים לאילוף יומיומי, מתאימים לגורים ולכלבים בוגרים.',
      34.90::numeric,
      null::numeric,
      null::numeric,
      'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=900&auto=format&fit=crop',
      'חטיפים',
      'dog'::public.pet_type,
      false,
      array['עוף']::text[],
      'MIPO',
      '180 גרם',
      193.88::numeric,
      'עוף, בטטה, גליצרין צמחי, מינרלים',
      '["קל לחיתוך", "מתאים לאילוף", "דל שומן"]'::jsonb,
      '{"texture": "soft"}'::jsonb,
      'all',
      'all',
      array['low fat']::text[],
      array[]::text[],
      array['משקל']::text[],
      88::numeric,
      null::numeric
    ),
    (
      'MIPO-TOY-001',
      'כדור משחק עמיד',
      'כדור גומי עמיד למשחקי זריקה, נשיכה ופעילות יומית.',
      29.90::numeric,
      null::numeric,
      null::numeric,
      'https://images.unsplash.com/photo-1529472119196-cb724127a98e?w=900&auto=format&fit=crop',
      'צעצועים',
      'dog'::public.pet_type,
      false,
      array[]::text[],
      'MIPO',
      null,
      null::numeric,
      'גומי טבעי',
      '["עמיד", "קל לניקוי", "מעודד פעילות"]'::jsonb,
      '{"diameter": "7cm"}'::jsonb,
      'all',
      'all',
      array[]::text[],
      array[]::text[],
      array[]::text[],
      86::numeric,
      null::numeric
    ),
    (
      'MIPO-BED-001',
      'מיטה אורתופדית MIPO Cloud',
      'מיטה רכה עם תמיכה אורתופדית לכלבים וחתולים, כיסוי נשלף לכביסה.',
      189.90::numeric,
      229.90::numeric,
      169.90::numeric,
      'https://images.unsplash.com/photo-1568572933382-74d440642117?w=900&auto=format&fit=crop',
      'מיטות',
      'all'::public.pet_type,
      true,
      array[]::text[],
      'MIPO',
      null,
      null::numeric,
      'ספוג זיכרון, בד מיקרופייבר',
      '["תמיכה במפרקים", "כיסוי נשלף", "מתאים לכל עונה"]'::jsonb,
      '{"sizes": ["S", "M", "L"]}'::jsonb,
      'all',
      'all',
      array[]::text[],
      array[]::text[],
      array['מפרקים']::text[],
      91::numeric,
      null::numeric
    ),
    (
      'MIPO-COLLAR-001',
      'קולר מתכוונן עם תג QR',
      'קולר נוח עם נקודת חיבור לתג זיהוי ו-QR לפרופיל חיית המחמד.',
      59.90::numeric,
      null::numeric,
      null::numeric,
      'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=900&auto=format&fit=crop',
      'אביזרים',
      'all'::public.pet_type,
      false,
      array[]::text[],
      'MIPO',
      null,
      null::numeric,
      'ניילון רך, אבזם פלסטיק מחוזק',
      '["מתכוונן", "קל משקל", "מוכן לתג QR"]'::jsonb,
      '{"sizes": ["S", "M", "L"], "colors": ["mint", "coral", "navy"]}'::jsonb,
      'all',
      'all',
      array[]::text[],
      array[]::text[],
      array[]::text[],
      87::numeric,
      null::numeric
    ),
    (
      'MIPO-DIGESTIVE-001',
      'Digestive Care פרוביוטיקה',
      'תוסף פרוביוטיקה לעיכול רגיש לכלבים וחתולים, לשימוש יומיומי לפי המלצת וטרינר.',
      79.90::numeric,
      89.90::numeric,
      null::numeric,
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&auto=format&fit=crop',
      'בריאות',
      'all'::public.pet_type,
      true,
      array[]::text[],
      'MIPO Vet',
      '60 כמוסות',
      1.33::numeric,
      'פרוביוטיקה, פרה-ביוטיקה, סיבים מסיסים',
      '["תמיכה בעיכול", "מתאים לאחר שינוי מזון", "לכלבים וחתולים"]'::jsonb,
      '{"servings": 60}'::jsonb,
      'all',
      'all',
      array['digestive']::text[],
      array[]::text[],
      array['עיכול']::text[],
      94::numeric,
      null::numeric
    ),
    (
      'MIPO-JOINT-001',
      'Joint Support חטיפי מפרקים',
      'חטיפי תמיכה במפרקים עם גלוקוזמין וכונדרואיטין לכלבים בוגרים וסניורים.',
      99.90::numeric,
      119.90::numeric,
      89.90::numeric,
      'https://images.unsplash.com/photo-1582798358481-d199fb7347bb?w=900&auto=format&fit=crop',
      'בריאות',
      'dog'::public.pet_type,
      true,
      array['בקר']::text[],
      'MIPO Vet',
      '120 גרם',
      749.17::numeric,
      'גלוקוזמין, כונדרואיטין, MSM, שמן סלמון',
      '["תמיכה במפרקים", "מתאים לכלבים מבוגרים", "קל לתת כחטיף"]'::jsonb,
      '{"active": "glucosamine"}'::jsonb,
      'senior',
      'all',
      array['joint']::text[],
      array[]::text[],
      array['מפרקים']::text[],
      93::numeric,
      null::numeric
    ),
    (
      'MIPO-CAT-URINARY-001',
      'Urinary Balance לחתולים',
      'מזון יבש לחתולים עם תמיכה בדרכי השתן, איזון מינרלים ו-pH.',
      179.90::numeric,
      null::numeric,
      null::numeric,
      'https://images.unsplash.com/photo-1574144113084-b6f450cc5e0c?w=900&auto=format&fit=crop',
      'בריאות',
      'cat'::public.pet_type,
      true,
      array['עוף']::text[],
      'MIPO Vet',
      '3 ק״ג',
      59.97::numeric,
      'עוף, אורז, חמוציות, מגנזיום מבוקר, טאורין',
      '["תמיכה בדרכי השתן", "איזון pH", "מתאים לחתולי בית"]'::jsonb,
      '{"ph": "controlled"}'::jsonb,
      'adult',
      null,
      array['urinary']::text[],
      array[]::text[],
      array['שתן']::text[],
      95::numeric,
      3780::numeric
    ),
    (
      'MIPO-SKIN-OMEGA-001',
      'Skin & Coat אומגה 3',
      'שמן אומגה 3 לעור ופרווה מבריקה, מתאים לכלבים וחתולים.',
      69.90::numeric,
      null::numeric,
      null::numeric,
      'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=900&auto=format&fit=crop',
      'בריאות',
      'all'::public.pet_type,
      false,
      array[]::text[],
      'MIPO Vet',
      '250 מ״ל',
      279.60::numeric,
      'שמן סלמון, אומגה 3, EPA, DHA',
      '["עור בריא", "פרווה מבריקה", "תמיכה אנטי דלקתית"]'::jsonb,
      '{"serving": "by weight"}'::jsonb,
      'all',
      'all',
      array['skin']::text[],
      array[]::text[],
      array['עור']::text[],
      92::numeric,
      null::numeric
    )
),
updated as (
  update public.business_products product
  set
    business_id = 'cf941cc4-e1d1-4d7c-8122-a5df81a1e53c',
    name = seed.name,
    description = seed.description,
    price = seed.price,
    original_price = seed.original_price,
    sale_price = seed.sale_price,
    image_url = seed.image_url,
    images = array[seed.image_url]::text[],
    category = seed.category,
    in_stock = true,
    is_featured = seed.is_featured,
    pet_type = seed.pet_type,
    flavors = seed.flavors,
    brand = seed.brand,
    weight_unit = seed.weight_unit,
    price_per_weight = seed.price_per_weight,
    ingredients = seed.ingredients,
    benefits = seed.benefits,
    product_attributes = seed.product_attributes,
    life_stage = seed.life_stage,
    dog_size = seed.dog_size,
    special_diet = seed.special_diet,
    breed_tags = seed.breed_tags,
    medical_tags = seed.medical_tags,
    safety_score = seed.safety_score,
    kcal_per_kg = seed.kcal_per_kg,
    updated_at = now()
  from seed_products seed
  where product.sku = seed.sku
  returning product.sku
)
insert into public.business_products (
  business_id,
  sku,
  name,
  description,
  price,
  original_price,
  sale_price,
  image_url,
  images,
  category,
  in_stock,
  is_featured,
  pet_type,
  flavors,
  brand,
  weight_unit,
  price_per_weight,
  ingredients,
  benefits,
  product_attributes,
  life_stage,
  dog_size,
  special_diet,
  breed_tags,
  medical_tags,
  safety_score,
  kcal_per_kg
)
select
  'cf941cc4-e1d1-4d7c-8122-a5df81a1e53c',
  seed.sku,
  seed.name,
  seed.description,
  seed.price,
  seed.original_price,
  seed.sale_price,
  seed.image_url,
  array[seed.image_url]::text[],
  seed.category,
  true,
  seed.is_featured,
  seed.pet_type,
  seed.flavors,
  seed.brand,
  seed.weight_unit,
  seed.price_per_weight,
  seed.ingredients,
  seed.benefits,
  seed.product_attributes,
  seed.life_stage,
  seed.dog_size,
  seed.special_diet,
  seed.breed_tags,
  seed.medical_tags,
  seed.safety_score,
  seed.kcal_per_kg
from seed_products seed
where not exists (
  select 1 from public.business_products existing where existing.sku = seed.sku
);
