import { createHash } from "node:crypto";
import * as XLSX from "@e965/xlsx";

// Reading a supplier file, on the server, without losing anything.
//
// The browser version read six columns out of a hundred and nineteen and threw
// the rest away before the server ever saw them. Here every column is kept: the
// row is stored as it arrived, and deciding what a column means is a separate
// step that can be corrected and replayed later.
//
// Files come from outside, so the limits below are load-bearing rather than
// defensive decoration.

export const MAX_FILE_BYTES = 25 * 1024 * 1024;
export const MAX_ROWS = 50_000;
export const MAX_COLUMNS = 500;
export const MAX_CELL_LENGTH = 10_000;

export class ImportParseError extends Error {
  constructor(message, code) {
    super(message);
    this.name = "ImportParseError";
    this.code = code;
    this.statusCode = 400;
  }
}

// A cell beginning with one of these is executed by Excel when the file is
// opened. Supplier data has no legitimate reason to contain a formula, so the
// value is kept verbatim for the record and neutralised on the way out.
const FORMULA_PREFIXES = ["=", "+", "-", "@", "\t", "\r"];

export const isFormulaLike = (value) => {
  if (typeof value !== "string" || value.length === 0) return false;
  return FORMULA_PREFIXES.includes(value[0]);
};

// Prefixing with an apostrophe is the standard neutralisation: the text still
// reads correctly to a person and is inert to the spreadsheet.
export const neutralizeFormula = (value) => (isFormulaLike(value) ? `'${value}` : value);

// The same header arrives spelled differently between exports: straight quotes
// one month, Hebrew gershayim the next, a trailing space the month after. The
// normalised form is what mappings are matched on; the original is what is
// shown to a person.
export const normalizeHeader = (header) =>
  String(header ?? "")
    .replace(/[׳״‘’“”]/g, '"')
    .replace(/\s+/g, " ")
    .replace(/‏|‎/g, "")
    .trim()
    .toLowerCase();

const normalizeCell = (value) => {
  if (value === null || value === undefined) return null;
  if (value instanceof Date) return value.toISOString();
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (typeof value === "boolean") return value;

  const text = String(value).replace(/‏|‎/g, "").trim();
  if (!text) return null;
  return text.length > MAX_CELL_LENGTH ? text.slice(0, MAX_CELL_LENGTH) : text;
};

export const hashRow = (raw) =>
  createHash("sha256").update(JSON.stringify(raw)).digest("hex");

export const hashFile = (buffer) =>
  createHash("sha256").update(buffer).digest("hex");

// Two columns can carry the same header — the reference file has four columns
// called מטבע. Suffixing keeps them distinct instead of silently overwriting
// one with the other, which is exactly the kind of loss this engine exists to
// prevent.
const buildHeaderNames = (headerRow) => {
  const seen = new Map();
  return headerRow.map((cell, index) => {
    const original = String(cell ?? "").replace(/‏|‎/g, "").trim();
    const base = original || `column_${index + 1}`;
    const count = seen.get(base) || 0;
    seen.set(base, count + 1);
    return count === 0 ? base : `${base}.${count}`;
  });
};

/**
 * Reads a spreadsheet into headers plus one raw object per row.
 *
 * @param {Buffer} buffer   the uploaded file
 * @param {object} options  sheetName and headerRow, both from the supplier profile
 */
export const parseSpreadsheet = (buffer, options = {}) => {
  if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
    throw new ImportParseError("The uploaded file is empty", "EMPTY_FILE");
  }
  if (buffer.length > MAX_FILE_BYTES) {
    throw new ImportParseError(
      `The file is larger than the ${Math.floor(MAX_FILE_BYTES / 1024 / 1024)}MB limit`,
      "FILE_TOO_LARGE",
    );
  }

  let workbook;
  try {
    // Formulas are never evaluated. Only the value the writing application
    // cached is read, so a cell containing =cmd|'/c calc'!A1 contributes its
    // stored result and nothing else.
    //
    // Known limit: a formula saved with no cached result is dropped by the
    // reader before this code sees it, and arrives as an empty cell. Excel and
    // ERP exports always write cached values, so this shows up with files
    // generated by libraries rather than with supplier deliveries. The column
    // itself is still present on every row, so the shape of the data is intact
    // even when such a value is missing.
    //
    // cellDates on so a date is a Date rather than a serial number.
    workbook = XLSX.read(buffer, {
      type: "buffer",
      cellDates: true,
      cellFormula: false,
      cellHTML: false,
      dense: false,
    });
  } catch (error) {
    throw new ImportParseError(`The file could not be read: ${error.message}`, "UNREADABLE_FILE");
  }

  const sheetName = options.sheetName && workbook.SheetNames.includes(options.sheetName)
    ? options.sheetName
    : workbook.SheetNames[0];

  if (!sheetName) {
    throw new ImportParseError("The file contains no sheets", "NO_SHEETS");
  }

  const sheet = workbook.Sheets[sheetName];
  const grid = XLSX.utils.sheet_to_json(sheet, {
    header: 1,
    raw: true,
    defval: null,
    // Blank rows are kept so a row's index still matches its position in the
    // file. They are skipped below instead: an error that says "row 214" has
    // to mean row 214 when the person opens the spreadsheet.
    blankrows: true,
  });

  const headerRowIndex = Math.max(1, Number(options.headerRow) || 1) - 1;
  if (grid.length <= headerRowIndex) {
    throw new ImportParseError(
      `The sheet has no row ${headerRowIndex + 1} to read headers from`,
      "NO_HEADER_ROW",
    );
  }

  const headerCells = grid[headerRowIndex] || [];
  if (headerCells.length === 0) {
    throw new ImportParseError("The header row is empty", "EMPTY_HEADER_ROW");
  }
  if (headerCells.length > MAX_COLUMNS) {
    throw new ImportParseError(
      `The sheet has ${headerCells.length} columns, over the ${MAX_COLUMNS} limit`,
      "TOO_MANY_COLUMNS",
    );
  }

  const headers = buildHeaderNames(headerCells);
  const rows = [];
  const formulaCells = [];
  let truncated = false;

  for (let index = headerRowIndex + 1; index < grid.length; index += 1) {
    if (rows.length >= MAX_ROWS) {
      truncated = true;
      break;
    }

    const cells = grid[index] || [];
    const raw = {};
    let hasValue = false;

    headers.forEach((header, column) => {
      const value = normalizeCell(cells[column]);
      if (value !== null && value !== "") hasValue = true;

      if (isFormulaLike(value)) {
        formulaCells.push({ row: index + 1, column: header });
        raw[header] = neutralizeFormula(value);
        return;
      }

      raw[header] = value;
    });

    // A spacer row between sections is not a product.
    if (!hasValue) continue;

    rows.push({
      // The spreadsheet's own row number, so a person can open the file and
      // find the row an error refers to.
      rowNumber: index + 1,
      raw,
      rawHash: hashRow(raw),
    });
  }

  // A file that parses but holds nothing is the wrong file, a corrupted one, or
  // the wrong sheet. Failing here is far clearer than creating an import run
  // with no rows and letting someone wonder why nothing happened.
  if (rows.length === 0) {
    throw new ImportParseError(
      `Sheet "${sheetName}" has headers but no data rows`,
      "NO_DATA_ROWS",
    );
  }

  return {
    sheetName,
    sheetNames: workbook.SheetNames,
    headers,
    normalizedHeaders: headers.map(normalizeHeader),
    rows,
    truncated,
    formulaCells,
  };
};

/**
 * Column-level accounting: which of the file's columns hold data at all.
 *
 * A column that is empty in every row is a decision waiting to be made, not a
 * mapping to write. In the reference delivery 62 of 119 columns are empty,
 * including every one the specification asks to convert into dynamic
 * attributes.
 */
export const summarizeColumns = (headers, rows) =>
  headers.map((header) => {
    let filled = 0;
    for (const row of rows) {
      const value = row.raw[header];
      if (value !== null && value !== undefined && value !== "") filled += 1;
    }
    return {
      source_field: header,
      normalized_source_field: normalizeHeader(header),
      filled_count: filled,
      total_rows: rows.length,
      is_empty: filled === 0,
    };
  });
