// src/petFactResolution.js — what happens when a fact already has a value.
//
// Pure, like petFactRegistry.js: in go the incoming fact, the facts currently
// open for that key, and the definition; out come the writes to perform. No
// database, so every case in docs/pet-intelligence/45-PROVENANCE-CONTRACT.md
// is a unit test.
//
// The first question is not "who wins" but "is this a conflict at all".
// pet_fact_definitions.volatile decides: two weights are two truths about a
// changing quantity and never disagree, while two answers about a neuter
// status do.

import { SOURCE_RANK } from "./petFactRegistry.js";

export const OUTCOMES = Object.freeze({
  CREATED: "CREATED",
  UNCHANGED: "UNCHANGED",
  SUPERSEDED: "SUPERSEDED",
  BACKDATED: "BACKDATED",
  OUTRANKED: "OUTRANKED",
  DISPUTED: "DISPUTED",
});

const VALUE_COLUMNS = [
  "value_text", "value_number", "value_boolean", "value_date",
  "value_timestamp", "value_json", "value_ref_id",
];

// pg hands timestamps back as Date objects, and String(date) drops the
// milliseconds -- which is enough to make a fact's effective_to land before its
// own effective_from when two writes happen inside the same second.
const time = (value) => {
  const parsed = value instanceof Date ? value : new Date(String(value ?? ""));
  return Number.isNaN(parsed.getTime()) ? 0 : parsed.getTime();
};

const iso = (millis) => new Date(millis).toISOString();

const sameValue = (a, b) => VALUE_COLUMNS.every((column) => {
  const left = a?.[column] ?? null;
  const right = b?.[column] ?? null;
  if (left === null || right === null) return left === right;
  if (column === "value_number") return Number(left) === Number(right);
  if (column === "value_json") return JSON.stringify(left) === JSON.stringify(right);
  if (column === "value_date" || column === "value_timestamp") return time(left) === time(right);
  return String(left) === String(right);
});

// A verification that means a human has since looked, for the fourth
// tie-break. DISPUTED and REJECTED are not standing, they are open questions.
const VERIFIED_STANDING = new Set(["USER_CONFIRMED", "VET_CONFIRMED"]);

const rankOf = (fact) => SOURCE_RANK[fact?.source_type] ?? Number.MAX_SAFE_INTEGER;

const openFactsOf = (currentFacts) => (currentFacts || [])
  .filter((fact) => fact && fact.effective_to === null && fact.status !== "RETRACTED");

const insertOp = (fact, extra) => ({ op: "insert", fact: { ...fact, ...extra } });

const closeOp = (factId, { status, effectiveTo, supersededByFactId = null, reason }) => ({
  op: "close",
  factId,
  status,
  effectiveTo,
  supersededByFactId,
  reason,
});

/**
 * Decide the writes for one incoming fact.
 *
 * @param {object} definition the pet_fact_definitions row
 * @param {object} incoming   the validated fact from validateFactWrite
 * @param {object[]} currentFacts the rows already open for (pet, namespace, key)
 * @param {string} newFactId  the id the incoming fact will get, generated by
 *                            the caller so a close operation can point at it
 * @returns {{outcome: string, operations: object[]}}
 */
export const planFactWrite = ({
  definition,
  incoming,
  currentFacts = [],
  newFactId,
  now = new Date(),
}) => {
  const open = openFactsOf(currentFacts);
  const nowMs = now.getTime();

  // Multi-valued keys are multiple rows, not arrays: health.allergy with
  // cardinality multi means one row per allergen, each with its own onset,
  // source and resolution. A second allergen does not supersede the first.
  if (definition.cardinality === "multi") {
    if (open.some((fact) => sameValue(fact, incoming))) {
      return { outcome: OUTCOMES.UNCHANGED, operations: [] };
    }
    return {
      outcome: OUTCOMES.CREATED,
      operations: [insertOp(incoming, {
        id: newFactId, status: "CURRENT", effective_to: null, superseded_by_fact_id: null,
      })],
    };
  }

  if (open.length === 0) {
    return {
      outcome: OUTCOMES.CREATED,
      operations: [insertOp(incoming, {
        id: newFactId, status: "CURRENT", effective_to: null, superseded_by_fact_id: null,
      })],
    };
  }

  // Recomputation is not news, and neither is an owner re-saving a form.
  if (open.length === 1 && sameValue(open[0], incoming)) {
    return { outcome: OUTCOMES.UNCHANGED, operations: [] };
  }

  const incomingFrom = time(incoming.effective_from);
  const incomingObserved = time(incoming.observed_at);

  // --- volatile keys: a later value supersedes, and that is all ------------
  if (definition.volatile) {
    const latest = open.reduce((a, b) => (time(a.observed_at) >= time(b.observed_at) ? a : b));

    // A value observed before the current one is history arriving late — a
    // March document uploaded in September. It takes the period before the
    // current fact rather than replacing it.
    if (incomingObserved < time(latest.observed_at)) {
      const effectiveTo = iso(Math.max(time(latest.effective_from), incomingFrom));
      return {
        outcome: OUTCOMES.BACKDATED,
        operations: [insertOp(incoming, {
          id: newFactId,
          status: "SUPERSEDED",
          effective_to: effectiveTo,
          superseded_by_fact_id: latest.id,
        })],
      };
    }

    const effectiveTo = iso(Math.max(incomingFrom, ...open.map((fact) => time(fact.effective_from))));
    return {
      outcome: OUTCOMES.SUPERSEDED,
      operations: [
        ...open.map((fact) => closeOp(fact.id, {
          status: "SUPERSEDED",
          effectiveTo,
          supersededByFactId: newFactId,
          reason: "a later value was recorded",
        })),
        insertOp(incoming, {
          id: newFactId, status: "CURRENT", effective_to: null, superseded_by_fact_id: null,
        }),
      ],
    };
  }

  // --- stable keys: an overlapping disagreement is a real conflict ---------
  const incomingRank = rankOf(incoming);
  const bestCurrent = open.reduce((a, b) => (rankOf(a) <= rankOf(b) ? a : b));
  const currentRank = rankOf(bestCurrent);

  const incomingWins = () => {
    if (incomingRank !== currentRank) return incomingRank < currentRank;
    // observed_at, not created_at: a March document describes March.
    const currentObserved = time(bestCurrent.observed_at);
    if (incomingObserved !== currentObserved) return incomingObserved > currentObserved;
    const incomingStanding = VERIFIED_STANDING.has(incoming.verification_status);
    const currentStanding = VERIFIED_STANDING.has(bestCurrent.verification_status);
    if (incomingStanding !== currentStanding) return incomingStanding;
    return null; // still tied
  };

  const verdict = incomingWins();

  if (verdict === true) {
    const effectiveTo = iso(Math.max(incomingFrom, ...open.map((fact) => time(fact.effective_from))));
    return {
      outcome: OUTCOMES.SUPERSEDED,
      operations: [
        ...open.map((fact) => closeOp(fact.id, {
          status: "SUPERSEDED",
          effectiveTo,
          supersededByFactId: newFactId,
          reason: "a stronger source disagreed",
        })),
        insertOp(incoming, {
          id: newFactId, status: "CURRENT", effective_to: null, superseded_by_fact_id: null,
        }),
      ],
    };
  }

  if (verdict === false) {
    // The weaker assertion is still recorded. Discarding it would lose the
    // evidence that two sources disagreed, which is exactly the thing a vet
    // asks about a year later.
    return {
      outcome: OUTCOMES.OUTRANKED,
      operations: [insertOp(incoming, {
        id: newFactId,
        status: "SUPERSEDED",
        effective_to: iso(Math.max(incomingFrom, nowMs)),
        superseded_by_fact_id: bestCurrent.id,
      })],
    };
  }

  // Equal rank, same observation time, same standing, different values. Never
  // coin-flip: both stay open and flagged, and a human decides. Until then the
  // restrictive reading applies to clinical keys — a disputed chicken allergy
  // keeps chicken excluded.
  return {
    outcome: OUTCOMES.DISPUTED,
    operations: [
      ...open
        .filter((fact) => fact.status !== "DISPUTED")
        .map((fact) => ({ op: "dispute", factId: fact.id, reason: "a source of equal standing disagreed" })),
      insertOp(incoming, {
        id: newFactId, status: "DISPUTED", effective_to: null, superseded_by_fact_id: null,
      }),
    ],
  };
};

/**
 * The value a reader should use, given every open row for one key.
 *
 * Returns null when the key is disputed and the caller asked for the strict
 * reading: a clinical question with two answers has no single answer, and
 * returning either one of them is how a restrictive rule gets bypassed.
 */
export const currentValueOf = (openFacts, { definition } = {}) => {
  const open = openFactsOf(openFacts);
  if (open.length === 0) return null;
  if (open.some((fact) => fact.status === "DISPUTED")) {
    return { disputed: true, facts: open, fact: null };
  }
  if (definition?.cardinality === "multi") {
    return { disputed: false, facts: open, fact: null };
  }
  const fact = open.reduce((a, b) => (
    time(a.observed_at) >= time(b.observed_at) ? a : b
  ));
  return { disputed: false, facts: open, fact };
};
