export const fallbackBreeds = [
  {
    id: "dog-golden-retriever",
    breed_name: "Golden Retriever",
    breed_name_he: "גולדן רטריבר",
    pet_type: "dog",
    life_expectancy_years: "10-12",
    description_he: "כלב משפחתי, חכם וידידותי מאוד. מתאים לבית פעיל, ילדים ואילוף חיובי.",
    affection_family: 5,
    kids_friendly: 5,
    dog_friendly: 5,
    shedding_level: 4,
    grooming_freq: 3,
    drooling_level: 2,
    stranger_openness: 5,
    playfulness: 5,
    watchdog_nature: 3,
    trainability: 5,
    energy_level: 4,
    barking_level: 3,
    mental_needs: 4,
    size_category: "large",
    weight_range_kg: "25-34",
    image_url: null,
  },
  {
    id: "dog-labrador-retriever",
    breed_name: "Labrador Retriever",
    breed_name_he: "לברדור רטריבר",
    pet_type: "dog",
    life_expectancy_years: "10-12",
    description_he: "חברותי, יציב ואנרגטי. זקוק לפעילות יומית ומתאים מאוד למשפחות.",
    affection_family: 5,
    kids_friendly: 5,
    dog_friendly: 5,
    shedding_level: 4,
    grooming_freq: 2,
    drooling_level: 2,
    stranger_openness: 5,
    playfulness: 5,
    watchdog_nature: 3,
    trainability: 5,
    energy_level: 5,
    barking_level: 3,
    mental_needs: 4,
    size_category: "large",
    weight_range_kg: "25-36",
    image_url: null,
  },
  {
    id: "dog-pomeranian",
    breed_name: "Pomeranian",
    breed_name_he: "פומרניאן",
    pet_type: "dog",
    life_expectancy_years: "12-16",
    description_he: "כלב קטן, ערני ובטוח בעצמו. מתאים לדירה אך דורש טיפוח פרווה קבוע.",
    affection_family: 4,
    kids_friendly: 3,
    dog_friendly: 3,
    shedding_level: 4,
    grooming_freq: 4,
    drooling_level: 1,
    stranger_openness: 3,
    playfulness: 4,
    watchdog_nature: 4,
    trainability: 4,
    energy_level: 3,
    barking_level: 4,
    mental_needs: 3,
    size_category: "small",
    weight_range_kg: "2-4",
    image_url: null,
  },
  {
    id: "dog-border-collie",
    breed_name: "Border Collie",
    breed_name_he: "בורדר קולי",
    pet_type: "dog",
    life_expectancy_years: "12-15",
    description_he: "אחד הגזעים החכמים ביותר. צריך עבודה מנטלית, תנועה ואתגרים קבועים.",
    affection_family: 4,
    kids_friendly: 4,
    dog_friendly: 4,
    shedding_level: 3,
    grooming_freq: 3,
    drooling_level: 1,
    stranger_openness: 3,
    playfulness: 5,
    watchdog_nature: 4,
    trainability: 5,
    energy_level: 5,
    barking_level: 4,
    mental_needs: 5,
    size_category: "medium",
    weight_range_kg: "14-22",
    image_url: null,
  },
  {
    id: "cat-domestic-shorthair",
    breed_name: "Domestic Shorthair",
    breed_name_he: "חתול בית קצר שיער",
    pet_type: "cat",
    life_expectancy_years: "12-18",
    description_he: "חתול נפוץ, עמיד ומגוון באופי. לרוב קל לטיפול ומתאים לבית שקט או פעיל.",
    affection_family: 4,
    kids_friendly: 4,
    dog_friendly: 3,
    shedding_level: 3,
    grooming_freq: 1,
    drooling_level: 1,
    stranger_openness: 3,
    playfulness: 4,
    watchdog_nature: 1,
    trainability: 3,
    energy_level: 3,
    barking_level: 1,
    mental_needs: 3,
    size_category: "medium",
    weight_range_kg: "3-6",
    image_url: null,
  },
  {
    id: "cat-persian",
    breed_name: "Persian",
    breed_name_he: "פרסי",
    pet_type: "cat",
    life_expectancy_years: "12-17",
    description_he: "חתול רגוע וביתי עם פרווה ארוכה. דורש הברשה תכופה וטיפוח עיניים.",
    affection_family: 4,
    kids_friendly: 3,
    dog_friendly: 2,
    shedding_level: 4,
    grooming_freq: 5,
    drooling_level: 1,
    stranger_openness: 2,
    playfulness: 2,
    watchdog_nature: 1,
    trainability: 2,
    energy_level: 2,
    barking_level: 1,
    mental_needs: 2,
    size_category: "medium",
    weight_range_kg: "3-6",
    image_url: null,
  },
  {
    id: "cat-maine-coon",
    breed_name: "Maine Coon",
    breed_name_he: "מיין קון",
    pet_type: "cat",
    life_expectancy_years: "12-15",
    description_he: "חתול גדול, חברותי וסקרן. צריך העשרה, משחק וטיפוח פרווה קבוע.",
    affection_family: 5,
    kids_friendly: 5,
    dog_friendly: 4,
    shedding_level: 4,
    grooming_freq: 4,
    drooling_level: 1,
    stranger_openness: 4,
    playfulness: 4,
    watchdog_nature: 1,
    trainability: 4,
    energy_level: 3,
    barking_level: 1,
    mental_needs: 4,
    size_category: "large",
    weight_range_kg: "5-9",
    image_url: null,
  },
  {
    id: "cat-siamese",
    breed_name: "Siamese",
    breed_name_he: "סיאמי",
    pet_type: "cat",
    life_expectancy_years: "12-20",
    description_he: "חתול חכם, קולני וחברתי מאוד. אוהב קשר יומיומי ומשחקים אינטראקטיביים.",
    affection_family: 5,
    kids_friendly: 4,
    dog_friendly: 3,
    shedding_level: 2,
    grooming_freq: 1,
    drooling_level: 1,
    stranger_openness: 4,
    playfulness: 5,
    watchdog_nature: 1,
    trainability: 4,
    energy_level: 4,
    barking_level: 5,
    mental_needs: 5,
    size_category: "medium",
    weight_range_kg: "3-6",
    image_url: null,
  },
];
