-- Multi-Agent System Tables

-- Bots registry
CREATE TABLE public.agent_bots (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  icon TEXT NOT NULL DEFAULT 'bot',
  color TEXT NOT NULL DEFAULT 'blue',
  is_active BOOLEAN NOT NULL DEFAULT true,
  capabilities JSONB DEFAULT '[]'::jsonb,
  config JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Task queue for all agents
CREATE TABLE public.agent_tasks (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  bot_id UUID REFERENCES public.agent_bots(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending_approval', 'approved', 'running', 'completed', 'failed', 'cancelled')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  task_type TEXT NOT NULL,
  payload JSONB DEFAULT '{}'::jsonb,
  result JSONB,
  requires_approval BOOLEAN NOT NULL DEFAULT false,
  approved_by UUID,
  approved_at TIMESTAMP WITH TIME ZONE,
  reason TEXT,
  expected_outcome TEXT,
  scheduled_for TIMESTAMP WITH TIME ZONE,
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Action logs for audit trail
CREATE TABLE public.agent_action_logs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  task_id UUID REFERENCES public.agent_tasks(id) ON DELETE CASCADE,
  bot_id UUID REFERENCES public.agent_bots(id) ON DELETE SET NULL,
  action_type TEXT NOT NULL,
  description TEXT NOT NULL,
  reason TEXT,
  expected_outcome TEXT,
  actual_outcome TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Daily briefs generated by orchestrator
CREATE TABLE public.agent_daily_briefs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  brief_date DATE NOT NULL DEFAULT CURRENT_DATE,
  summary TEXT NOT NULL,
  priorities JSONB DEFAULT '[]'::jsonb,
  kpis JSONB DEFAULT '{}'::jsonb,
  recommendations JSONB DEFAULT '[]'::jsonb,
  tasks_planned INTEGER DEFAULT 0,
  tasks_completed INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Agent conversations/chat history
CREATE TABLE public.agent_conversations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID,
  title TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  context JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE public.agent_messages (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  conversation_id UUID NOT NULL REFERENCES public.agent_conversations(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'bot')),
  content TEXT NOT NULL,
  bot_id UUID REFERENCES public.agent_bots(id) ON DELETE SET NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.agent_bots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_action_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_daily_briefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_messages ENABLE ROW LEVEL SECURITY;

-- Policies for admin access using has_role function
CREATE POLICY "Admins can manage bots" ON public.agent_bots FOR ALL USING (
  public.has_role(auth.uid(), 'admin')
);

CREATE POLICY "Admins can manage tasks" ON public.agent_tasks FOR ALL USING (
  public.has_role(auth.uid(), 'admin')
);

CREATE POLICY "Admins can view action logs" ON public.agent_action_logs FOR SELECT USING (
  public.has_role(auth.uid(), 'admin')
);

CREATE POLICY "System can insert action logs" ON public.agent_action_logs FOR INSERT WITH CHECK (true);

CREATE POLICY "Admins can manage daily briefs" ON public.agent_daily_briefs FOR ALL USING (
  public.has_role(auth.uid(), 'admin')
);

CREATE POLICY "Admins can manage conversations" ON public.agent_conversations FOR ALL USING (
  public.has_role(auth.uid(), 'admin')
);

CREATE POLICY "Admins can manage messages" ON public.agent_messages FOR ALL USING (
  EXISTS (SELECT 1 FROM public.agent_conversations c WHERE c.id = conversation_id AND 
    public.has_role(auth.uid(), 'admin'))
);

-- Insert default bots
INSERT INTO public.agent_bots (name, slug, description, icon, color, capabilities) VALUES
('PetID Ops Commander', 'orchestrator', 'מנהל המערכת הראשי - מתאם משימות, מתעדף לפי KPIs, ומנתב עבודה לבוטים', 'crown', 'purple', '["task_prioritization", "bot_coordination", "kpi_analysis", "daily_briefing"]'),
('Marketing Manager', 'marketing', 'מנהל קמפיינים, מבצעים, ואסטרטגיית שיווק', 'megaphone', 'pink', '["campaign_management", "promotion_planning", "audience_targeting"]'),
('Content Creator', 'content', 'יוצר תוכן לרשתות חברתיות, בלוג, ומיילים', 'pen-tool', 'cyan', '["content_generation", "social_posts", "email_copy", "blog_writing"]'),
('Ads Manager', 'ads', 'מנהל פרסום בגוגל, פייסבוק ואינסטגרם', 'target', 'orange', '["ad_creation", "budget_management", "performance_optimization"]'),
('WhatsApp Sales', 'whatsapp-sales', 'מכירות ושירות לקוחות בוואטסאפ', 'message-circle', 'green', '["lead_qualification", "sales_followup", "customer_support"]'),
('Store Operations', 'store-ops', 'ניהול מלאי, מחירים, וקטלוג מוצרים', 'store', 'blue', '["inventory_management", "pricing", "catalog_updates"]'),
('Fulfillment', 'fulfillment', 'ניהול הזמנות, משלוחים, והחזרות', 'truck', 'amber', '["order_processing", "shipping_management", "returns_handling"]'),
('Finance', 'finance', 'ניהול כספים, דוחות, והתאמות', 'wallet', 'emerald', '["financial_reports", "expense_tracking", "revenue_analysis"]'),
('Support', 'support', 'תמיכה טכנית ושירות לקוחות', 'headphones', 'indigo', '["ticket_management", "faq_responses", "escalation_handling"]'),
('Analytics', 'analytics', 'ניתוח נתונים, דוחות, ותובנות', 'bar-chart-3', 'violet', '["data_analysis", "reporting", "insights_generation"]');

-- Create indexes for performance
CREATE INDEX idx_agent_tasks_status ON public.agent_tasks(status);
CREATE INDEX idx_agent_tasks_bot_id ON public.agent_tasks(bot_id);
CREATE INDEX idx_agent_tasks_priority ON public.agent_tasks(priority);
CREATE INDEX idx_agent_action_logs_bot_id ON public.agent_action_logs(bot_id);
CREATE INDEX idx_agent_messages_conversation ON public.agent_messages(conversation_id);

-- Update trigger for timestamps
CREATE TRIGGER update_agent_bots_updated_at BEFORE UPDATE ON public.agent_bots
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_agent_tasks_updated_at BEFORE UPDATE ON public.agent_tasks
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_agent_conversations_updated_at BEFORE UPDATE ON public.agent_conversations
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();