// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_DISABLED = import.meta.env.VITE_DISABLE_SUPABASE === "true";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const emptySubscription = { unsubscribe: () => undefined };

class DisabledSupabaseQuery {
  private singleResult = false;

  select() { return this; }
  insert() { return this; }
  update() { return this; }
  upsert() { return this; }
  delete() { return this; }
  eq() { return this; }
  neq() { return this; }
  gt() { return this; }
  gte() { return this; }
  lt() { return this; }
  lte() { return this; }
  like() { return this; }
  ilike() { return this; }
  is() { return this; }
  in() { return this; }
  not() { return this; }
  or() { return this; }
  contains() { return this; }
  containedBy() { return this; }
  rangeGt() { return this; }
  rangeGte() { return this; }
  rangeLt() { return this; }
  rangeLte() { return this; }
  rangeAdjacent() { return this; }
  overlaps() { return this; }
  textSearch() { return this; }
  match() { return this; }
  order() { return this; }
  limit() { return this; }
  range() { return this; }
  abortSignal() { return this; }
  csv() { return Promise.resolve({ data: "", error: null }); }
  geojson() { return Promise.resolve({ data: null, error: null }); }
  explain() { return Promise.resolve({ data: null, error: null }); }

  single() {
    this.singleResult = true;
    return this;
  }

  maybeSingle() {
    this.singleResult = true;
    return this;
  }

  then<TResult1 = { data: unknown; error: null }, TResult2 = never>(
    onfulfilled?: ((value: { data: unknown; error: null }) => TResult1 | PromiseLike<TResult1>) | null,
    onrejected?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
  ) {
    const value = { data: this.singleResult ? null : [], error: null };
    return Promise.resolve(value).then(onfulfilled, onrejected);
  }
}

const createDisabledSupabaseClient = () => ({
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: emptySubscription } }),
    signInWithPassword: async () => ({
      data: { user: null, session: null },
      error: { message: "Supabase auth is disabled in this AWS build" },
    }),
    signOut: async () => ({ error: null }),
    resetPasswordForEmail: async () => ({ data: {}, error: null }),
    updateUser: async () => ({ data: { user: null }, error: null }),
    verifyOtp: async () => ({ data: { user: null, session: null }, error: null }),
  },
  from: () => new DisabledSupabaseQuery(),
  rpc: () => new DisabledSupabaseQuery(),
  functions: {
    invoke: async () => ({ data: null, error: null }),
  },
  storage: {
    from: () => ({
      upload: async () => ({ data: null, error: { message: "Supabase storage is disabled in this AWS build" } }),
      remove: async () => ({ data: [], error: null }),
      getPublicUrl: () => ({ data: { publicUrl: "" } }),
      createSignedUrl: async () => ({ data: { signedUrl: "" }, error: null }),
    }),
  },
  channel: () => ({
    on: function on() { return this; },
    subscribe: function subscribe() { return this; },
    unsubscribe: () => "ok",
  }),
  removeChannel: () => undefined,
  removeAllChannels: () => undefined,
});

export const supabase: SupabaseClient<Database> = (
  SUPABASE_DISABLED || !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? createDisabledSupabaseClient()
    : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
) as SupabaseClient<Database>;
